service: secret-bar-crawl-api

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: python2.7
  environment:
    DYNAMODB_TEAM_TABLE: ${self:service}-teams-${opt:stage, self:provider.stage}
    DYNAMODB_BAR_TABLE: ${self:service}-bars-${opt:stage, self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TEAM_TABLE}"
        - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_BAR_TABLE}"

functions:
  listTeams:
    handler: teams/list.team
    events:
      - http:
          path: teams
          method: get
          cors: true

  createTeam:
    handler: teams/create.team
    events:
      - http:
          path: teams
          method: post
          cors: true

  getTeam:
    handler: teams/get.team
    events:
      - http:
          path: teams/{id}
          method: get
          cors: true

  updateTeam:
    handler: teams/update.team
    events:
      - http:
          path: teams/{id}
          method: put
          cors: true

  createMember:
    handler: teams/members/create.member
    events:
      - http:
          path: teams/{id}/members
          method: post
          cors: true

  deleteMember:
    handler: teams/members/delete.member
    events:
      - http:
          path: teams/{id}/members/{memberId}
          method: delete
          cors: true

  createScore:
    handler: teams/scores/create.score
    events:
      - http:
          path: teams/{id}/scores
          method: post
          cors: true
  
  updateScore:
    handler: teams/scores/update.score
    events:
      - http:
          path: teams/{id}/scores
          method: put
          cors: true

  createBonusPoints:
    handler: /teams/bonusPoints/create.bonusPoints
    events: 
      - http:
          path: teams/{id}/bonuspoints
          method: put
          cors: true

  listBar:
    handler: bars/list.bar
    events:
      - http:
          path: bars
          method: get
          cors: true

  createBar:
    handler: bars/create.bar
    events:
      - http:
          path: bars
          method: post
          cors: true
  getBar:
    handler: bars/get.bar
    events:
      - http:
          path: bars/{id}
          method: get
          cors: true

  updateBar:
    handler: bars/update.bar
    events:
      - http:
          path: bars/{id}
          method: put
          cors: true

resources:
  Resources:
    TeamsDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Delete
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_TEAM_TABLE}
    BarsDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Delete
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_BAR_TABLE}
